# Generated by Django 5.2.13 on 2026-05-01 18:29

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.PositiveIntegerField(db_index=True, unique=True)),
                ("prev_hash", models.CharField(max_length=64)),
                ("payload_json", models.JSONField(default=dict)),
                ("this_hash", models.CharField(max_length=64, unique=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("ts", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["seq"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_index",
                    models.PositiveIntegerField(
                        help_text="Order within the document — for stable citation references."
                    ),
                ),
                ("page_no", models.PositiveIntegerField(help_text="1-indexed.")),
                ("bbox_l", models.FloatField()),
                ("bbox_t", models.FloatField()),
                ("bbox_r", models.FloatField()),
                ("bbox_b", models.FloatField()),
                (
                    "coord_origin",
                    models.CharField(
                        choices=[
                            ("BOTTOMLEFT", "Bottom-left (PDF native, Docling)"),
                            ("TOPLEFT", "Top-left (image native, Gemini Vision)"),
                        ],
                        default="BOTTOMLEFT",
                        max_length=16,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "confidence",
                    models.FloatField(
                        default=1.0,
                        help_text="1.0 for digital-text Docling blocks; 0.0-1.0 self-elicited for Gemini Vision blocks.",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("DOCLING", "Docling (digital PDF parser)"),
                            ("GEMINI_VISION", "Gemini Vision (image OCR fallback)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "reason_if_low",
                    models.TextField(
                        blank=True,
                        help_text="Set by Gemini Vision when confidence < OCR_CONFIDENCE_THRESHOLD.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["document_id", "block_index"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RFP", "Request for Proposal (tender notice)"),
                            ("BIDDER_COVER", "Bidder cover letter / tender acceptance"),
                            ("BIDDER_AUDIT", "Bidder audited financial summary"),
                            ("BIDDER_GST", "Bidder GST registration certificate"),
                            ("BIDDER_DSC", "Bidder Class-3 DSC certificate"),
                            ("BIDDER_EXPERIENCE", "Bidder past performance statement"),
                            ("BIDDER_ISO", "Bidder ISO 9001 certificate"),
                            ("BIDDER_OTHER", "Bidder document (other)"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "bidder_code",
                    models.CharField(
                        blank=True,
                        help_text="A / B / C for bidder docs; blank for RFPs.",
                        max_length=1,
                    ),
                ),
                ("file", models.FileField(upload_to=core.models.document_upload_path)),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("sha256", models.CharField(db_index=True, max_length=64, unique=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["type", "bidder_code"],
                        name="core_docume_type_ec1d13_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. 'C-1', 'C-2', stable id within an RFP.",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("requirement_text", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("financial", "Financial"),
                            ("compliance", "Compliance"),
                            ("technical", "Technical"),
                        ],
                        max_length=32,
                    ),
                ),
                ("mandatory", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_clause_block",
                    models.ForeignKey(
                        blank=True,
                        help_text="Block in the RFP where this criterion was cited from.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="criteria_citing_this_clause",
                        to="core.block",
                    ),
                ),
                (
                    "rfp",
                    models.ForeignKey(
                        limit_choices_to={"type": "RFP"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="criteria",
                        to="core.document",
                    ),
                ),
            ],
            options={
                "ordering": ["rfp_id", "code"],
            },
        ),
        migrations.AddField(
            model_name="block",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="core.document",
            ),
        ),
        migrations.CreateModel(
            name="Fact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidder_code", models.CharField(max_length=1)),
                (
                    "value",
                    models.TextField(
                        blank=True, help_text="Extracted value as a string."
                    ),
                ),
                ("ocr_confidence", models.FloatField(default=1.0)),
                (
                    "raw_extraction_json",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full structured response from Gemini for this extraction.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to="core.criterion",
                    ),
                ),
                (
                    "evidence_blocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="facts_citing_this_block",
                        to="core.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeminiCallCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_sha256", models.CharField(db_index=True, max_length=64)),
                (
                    "image_sha256",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empty for text-only calls.",
                        max_length=64,
                    ),
                ),
                ("model", models.CharField(max_length=64)),
                ("response_json", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hits",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="How many times this cached entry has been served.",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prompt_sha256", "image_sha256", "model"),
                        name="gemini_cache_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Verdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bidder_code", models.CharField(max_length=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("ABSTAIN", "Abstain (needs human review)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        help_text="Identifier of the Rego rule that fired.",
                        max_length=128,
                    ),
                ),
                ("bindings_json", models.JSONField(blank=True, default=dict)),
                ("reason", models.TextField(blank=True)),
                ("decided_at", models.DateTimeField(auto_now_add=True)),
                (
                    "criterion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verdicts",
                        to="core.criterion",
                    ),
                ),
                (
                    "evidence_refs",
                    models.ManyToManyField(
                        blank=True,
                        related_name="verdicts_citing_this_block",
                        to="core.block",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OverrideRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_status",
                    models.CharField(
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("ABSTAIN", "Abstain (needs human review)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("ts", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verdict",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overrides",
                        to="core.verdict",
                    ),
                ),
            ],
            options={
                "ordering": ["-ts"],
            },
        ),
        migrations.AddConstraint(
            model_name="criterion",
            constraint=models.UniqueConstraint(
                fields=("rfp", "code"), name="criterion_rfp_code_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["document", "page_no"], name="core_block_documen_ce8d14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="block",
            index=models.Index(
                fields=["confidence"], name="core_block_confide_091a89_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="block",
            constraint=models.UniqueConstraint(
                fields=("document", "block_index"), name="block_doc_index_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="fact",
            index=models.Index(
                fields=["bidder_code"], name="core_fact_bidder__81cf05_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fact",
            constraint=models.UniqueConstraint(
                fields=("criterion", "bidder_code"), name="fact_criterion_bidder_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="verdict",
            index=models.Index(
                fields=["bidder_code", "status"], name="core_verdic_bidder__4bceb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verdict",
            index=models.Index(fields=["status"], name="core_verdic_status_353b59_idx"),
        ),
        migrations.AddConstraint(
            model_name="verdict",
            constraint=models.UniqueConstraint(
                fields=("criterion", "bidder_code"),
                name="verdict_criterion_bidder_unique",
            ),
        ),
    ]
