# Generated by Django 5.2.13 on 2026-05-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="criterion",
            options={
                "ordering": ["rfp_id", "code"],
                "verbose_name": "Criterion",
                "verbose_name_plural": "Criteria",
            },
        ),
    ]
