# Generated by Django 5.2.13 on 2026-05-02 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_criterion_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditentry",
            options={
                "ordering": ["seq"],
                "verbose_name": "Audit entry",
                "verbose_name_plural": "Audit entries",
            },
        ),
    ]
